package com.hubuandroid.mywechat.beans;

import com.hubuandroid.mywechat.R;

public class Datas {
        public static int[] icons = {
                R.mipmap.pic_01,
                R.mipmap.pic_02,
                R.mipmap.pic_03,
                R.mipmap.pic_04,
                R.mipmap.pic_11,
                R.mipmap.pic_05,
                R.mipmap.pic_06,
                R.mipmap.pic_07,
                R.mipmap.pic_08,
                R.mipmap.pic_09,
                R.mipmap.pic_10,
                R.mipmap.pic_03,
                R.mipmap.pic_03,
                R.mipmap.pic_04,
                R.mipmap.pic_05,
                R.mipmap.pic_06,
                R.mipmap.pic_07,
                R.mipmap.pic_03,
                R.mipmap.pic_04,
                R.mipmap.pic_05,
                R.mipmap.pic_06,
                R.mipmap.pic_07,
                R.mipmap.pic_08,
                R.mipmap.pic_09,
                R.mipmap.pic_10,
                R.mipmap.pic_11,
                R.mipmap.pic_11,
                R.mipmap.pic_08,
                R.mipmap.pic_09,
                R.mipmap.pic_10,
                R.mipmap.pic_11,
                R.mipmap.pic_05,
                R.mipmap.pic_06,
                R.mipmap.pic_07,
                R.mipmap.pic_08,
                R.mipmap.pic_09,
                R.mipmap.pic_10,
                R.mipmap.pic_03,
                R.mipmap.pic_04,
                R.mipmap.pic_05,
                R.mipmap.pic_06,
                R.mipmap.pic_07,
                R.mipmap.pic_08,
                R.mipmap.pic_09,
                R.mipmap.pic_10,
                R.mipmap.pic_11,
                R.mipmap.pic_11,
                R.mipmap.pic_12};
    }
